version: "3.8"
services:
  penpot-frontend:
    image: penpotapp/frontend:latest
    depends_on:
      - penpot-backend
      - penpot-exporter
    volumes:
      - penpot_assets:/opt/data
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.services.penpot-frontend.loadbalancer.server.scheme: http
      traefik.http.routers.penpot-frontend.rule: Host(`${PENPOT_DOMAIN}`)
      traefik.http.routers.penpot-frontend.entrypoints: websecure,web
      traefik.http.routers.penpot-frontend.tls.certResolver: leresolver
      traefik.http.routers.penpot-frontend.service: penpot-frontend
    networks:
      - default
      - traefik
    restart: always

  penpot-backend:
    image: penpotapp/backend:latest
    depends_on:
      penpot-postgres:
        condition: service_healthy
      penpot-redis:
        condition: service_healthy
    volumes:
      - penpot_assets:/opt/data
    environment:
      - PENPOT_PUBLIC_URI=https://${PENPOT_DOMAIN}
      - PENPOT_SECRET_KEY=${PENPOT_SECRET_KEY}
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=${POSTGRES_USER}
      - PENPOT_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - PENPOT_FLAGS=${PENPOT_FLAGS}
      - PENPOT_REDIS_URI=redis://penpot-redis/0
    networks:
      - default
    restart: always

  penpot-exporter:
    build:
      dockerfile: ./exporter.Dockerfile
    depends_on:
      - penpot-redis
    environment:
      - PENPOT_PUBLIC_URI=http://penpot-frontend:8080
      - PENPOT_REDIS_URI=redis://penpot-redis/0
    networks:
      - default
    restart: always

  penpot-postgres:
    image: postgres:16
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER}" || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - default
    restart: always

  penpot-redis:
    image: redis:7
    healthcheck:
      test: redis-cli PING
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - default
    restart: always

volumes:
  postgres:
  penpot_assets:
networks:
  default:
  traefik:
    name: traefik
    external: true
